name: CD

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    defaults:
      run:
        shell: bash

    env:
      KOBWEB_CLI_VERSION: 0.9.15

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Ensure Gradle is executable
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Query Browser Cache ID
        id: browser-cache-id
        run: echo "value=$(./gradlew -q kobwebBrowserCacheId)" >> $GITHUB_OUTPUT

      - name: Cache Browser Dependencies
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.browser-cache-id.outputs.value }}

      - name: Run Kobweb export
        run: ./gradlew kobwebExport -PkobwebExportLayout=STATIC -PkobwebBuildTarget=RELEASE -PkobwebReuseServer=false --stacktrace --no-daemon --info

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .kobweb/site/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4